export const AUTH_CONFIG = {
  ACCESS_TOKEN_TTL: '15m',
  REFRESH_TOKEN_TTL: '7d',
  BCRYPT_COST: 12,
  RATE_LIMIT_MAX: 10,
  RATE_LIMIT_WINDOW_MS: 60_000,
} as const;

export const DEFAULT_TENANT_ID = '00000000-0000-4000-a000-000000000001';

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DUPLICATE_DETECTED: 'ACCOUNT_DUPLICATE_DETECTED',
  ACCOUNT_TERRITORY_MISMATCH: 'ACCOUNT_TERRITORY_MISMATCH',
  ACCOUNT_CIRCULAR_HIERARCHY: 'ACCOUNT_CIRCULAR_HIERARCHY',
  ACCOUNT_CONFLICT: 'ACCOUNT_CONFLICT',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
