name: haversack

services:
  haversack-db:
    image: postgres:16-alpine
    container_name: haversack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: haversack
      POSTGRES_PASSWORD: haversack_dev
      POSTGRES_DB: haversack_dev
    ports:
      - '5432:5432'
    volumes:
      - haversack-postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - haversack-network

  haversack-redis:
    image: redis:7-alpine
    container_name: haversack-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - haversack-redis-data:/data
    networks:
      - haversack-network

volumes:
  haversack-postgres-data:
  haversack-redis-data:

networks:
  haversack-network:
    name: haversack-network
