import type { PrismaClient } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { BrandError } from './brand.service';

export interface LineCardProduct {
  name: string;
  sku: string;
  description: string | null;
  unitPrice: number;
  wholesalePrice: number | null;
  caseSize: number | null;
  certifications: string[];
  availabilityStatus: string;
}

export interface LineCardData {
  brandName: string;
  brandDescription: string | null;
  logoUrl: string | null;
  generatedDate: string;
  products: LineCardProduct[];
}

export async function fetchLineCardData(
  prisma: PrismaClient,
  tenantId: string,
  brandId: string,
): Promise<LineCardData> {
  const brand = await prisma.brand.findFirst({
    where: { id: brandId, tenantId },
  });

  if (!brand) {
    throw new BrandError('Brand not found', 'BRAND_NOT_FOUND');
  }

  const products = await prisma.product.findMany({
    where: {
      tenantId,
      brandId,
      isActive: true,
      availabilityStatus: { not: 'discontinued' },
    },
    orderBy: { name: 'asc' },
  });

  if (products.length === 0) {
    throw new BrandError(
      'No active products found for this brand — cannot generate line card.',
      'BRAND_NO_ACTIVE_PRODUCTS',
    );
  }

  return {
    brandName: brand.name,
    brandDescription: brand.description,
    logoUrl: brand.logoUrl,
    generatedDate: new Date().toISOString().split('T')[0]!,
    products: products.map((p) => ({
      name: p.name,
      sku: p.sku,
      description: p.description,
      unitPrice: Number(p.unitPrice),
      wholesalePrice: p.wholesalePrice ? Number(p.wholesalePrice) : null,
      caseSize: p.caseSize,
      certifications: p.certifications,
      availabilityStatus: p.availabilityStatus,
    })),
  };
}

export function generateLineCardPdf(data: LineCardData): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margin: 50,
      info: {
        Title: `${data.brandName} Line Card`,
        Author: 'Haversack Sales',
      },
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err: Error) => reject(err));

    // Header
    doc.fontSize(20).font('Helvetica-Bold').text(data.brandName, { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').text('Product Line Card', { align: 'center' });
    if (data.brandDescription) {
      doc.moveDown(0.3);
      doc.fontSize(9).text(data.brandDescription, { align: 'center' });
    }
    doc.moveDown(0.3);
    doc.fontSize(8).text(`Generated: ${data.generatedDate}`, { align: 'center' });
    doc.moveDown(1);

    // Separator
    doc.moveTo(50, doc.y).lineTo(562, doc.y).stroke();
    doc.moveDown(0.5);

    // Column headers
    const tableTop = doc.y;
    const colX = { name: 50, sku: 180, price: 280, wholesale: 340, caseSize: 410, certs: 450 };

    doc.fontSize(8).font('Helvetica-Bold');
    doc.text('Product', colX.name, tableTop, { width: 125 });
    doc.text('SKU', colX.sku, tableTop, { width: 95 });
    doc.text('Unit $', colX.price, tableTop, { width: 55 });
    doc.text('Whlse $', colX.wholesale, tableTop, { width: 65 });
    doc.text('Case', colX.caseSize, tableTop, { width: 35 });
    doc.text('Certifications', colX.certs, tableTop, { width: 112 });
    doc.moveDown(0.5);

    // Separator under headers
    doc.moveTo(50, doc.y).lineTo(562, doc.y).stroke();
    doc.moveDown(0.3);

    // Product rows
    doc.font('Helvetica').fontSize(8);
    for (const product of data.products) {
      // Check if we need a new page
      if (doc.y > 700) {
        doc.addPage();
        doc.y = 50;
      }

      const rowY = doc.y;
      doc.text(product.name, colX.name, rowY, { width: 125 });
      doc.text(product.sku, colX.sku, rowY, { width: 95 });
      doc.text(`$${product.unitPrice.toFixed(2)}`, colX.price, rowY, { width: 55 });
      doc.text(
        product.wholesalePrice ? `$${product.wholesalePrice.toFixed(2)}` : '—',
        colX.wholesale,
        rowY,
        { width: 65 },
      );
      doc.text(
        product.caseSize ? String(product.caseSize) : '—',
        colX.caseSize,
        rowY,
        { width: 35 },
      );
      doc.text(
        product.certifications.length > 0 ? product.certifications.join(', ') : '—',
        colX.certs,
        rowY,
        { width: 112 },
      );
      doc.moveDown(0.8);
    }

    // Footer
    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).stroke();
    doc.moveDown(0.5);
    doc.fontSize(7).font('Helvetica').text(
      `Generated by Haversack Sales Platform — ${data.products.length} products listed`,
      { align: 'center' },
    );

    doc.end();
  });
}

export async function generateLineCard(
  prisma: PrismaClient,
  tenantId: string,
  brandId: string,
): Promise<{ buffer: Buffer; filename: string }> {
  const data = await fetchLineCardData(prisma, tenantId, brandId);
  const buffer = await generateLineCardPdf(data);
  const safeName = data.brandName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
  const filename = `${safeName}-line-card-${data.generatedDate}.pdf`;

  return { buffer, filename };
}
